apiVersion: ingress.v1.haproxy.org/v1
kind: TCP
metadata:
  name: nats-cluster-tcp
  namespace: nats
  annotations:
    ingress.class: haproxy
spec:
  - name: nats-cluster-tcp
    frontend:
      name: nats-cluster
      tcplog: true
      binds:
        - name: bind2
          port: 4222
    service:
      name: $CLUSTER_NAME-nats
      port: 4222
