apiVersion: v1
kind: Service
metadata:
  name: xr-js-nats-headless-$CLUSTER_NAME
  namespace: nats
  labels:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: xr-js
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.11.4
  annotations:
    config.linkerd.io/opaque-ports: 4222,6222,7222,8222
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  publishNotReadyAddresses: true
  ports:
    - appProtocol: tcp
      name: nats
      port: 4222
      protocol: TCP
      targetPort: nats
    - appProtocol: tcp
      name: cluster
      port: 6222
      protocol: TCP
      targetPort: cluster
    - appProtocol: tcp
      name: gateway
      port: 7222
      protocol: TCP
      targetPort: gateway
    - appProtocol: http
      name: monitor
      port: 8222
      protocol: TCP
      targetPort: monitor
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: xr-js
    app.kubernetes.io/name: nats
  sessionAffinity: None
  type: ClusterIP
